### ISSUE TITLE
Drop a potentially irrelevant test

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-pygments#14]
I noticed a test that checks how an upstream lexer works: https://github.com/ansible-community/ansible-pygments/blob/86c1dd7/tests/test_lexer.py#L40.

@felixfontein do you know anything about this? I'm pretty sure that such sort of test belongs in the upstream project and not here. Any specific reason to keep it? I'd rather remove it.

**Comment by felixfontein** [comment]
That's from when that lexer was vendored to fix a bug. I forgot to remove it when the vendored YAML/Jinja2 lexer was removed (which I think was long before I added the test to antsibull, since I can't find that test in ansible/ansible - I think the test was mainly lying around on my HDD until I 'found' it when adding the lexer to antsibull, and decided to reactivate it).
