### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/ansible-pygments#16]
So we can start making progress, I'd really like to release a 0.1.0 version of this repo. Not having any release currently blocks ansible-community/antsibull#280 and ansible/ansible#73170.

**Comment by webknjaz** [comment]
Sure, let me handle this. I think I have some things uncommitted + the SCM versioning is still unsolved so I'll need to look into it more closely.

**Comment by webknjaz** [comment]
@felixfontein you should be able to trigger the release by using the manual invocation at this page https://github.com/ansible-community/ansible-pygments/actions/workflows/ci-cd.yml and typing in the version number. I recommend testing with an alpha release like `0.1.0a2` first.

I don't do this myself so that you'll have a chance to experience how the process works.

P.S. Currently, it uses the version you specify in the resulting artifacts and pushes that as a tag upon successful uploads to the package indexes. I think it could be extended to actually commit the change to `pyproject.toml` but I didn't spend time implementing that as it's not a blocker for us.

**Comment by felixfontein** [comment]
0.1.0 is released.

**Comment by webknjaz** [comment]
`sphinx-ansible-theme >= 0.7.0` now uses this.

**Comment by felixfontein** [comment]
antsibull's `main` branch as well.
